[package]
name = "Cosmic_Tidal_Pool"
version = "0.2.2"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["bevy_render", "shader_format_wesl"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"